version: '3.7'
services:
  micronaut-api:
    build:
      context: .
    image: rbarbioni/micronaut-api
    environment:
      - JAVA_OPTS=-server -XX:+UseG1GC -Xss256k -Xms128m -Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - JDBC_URL=jdbc:postgresql://db:5432/api
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=api
      - JDBC_PASS=api
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "5005:5005"
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure